### PR TITLE
fix: Do not pre-seed by default

### PR DESCRIPTION
**Pull request by razor-x**
I think it makes more sense to opt-in to the seed. This also contains a fix for docker signal handling. Otherwise the contains misbehaves and will not shutdown. And a fix so args can be passed in.

### CODE REVIEW

**Review by seveibar — APPROVED** [review]
yea i think that's fine

**Comment by seveibar** [comment]
I think the bundle size jumped recently fwiw

**Comment by seveibar** [comment]
The bundle is 7M bigger in this PR I think

**Comment by razor-x** [comment]
Ok that is odd as the new deps are not large 
image

**Comment by razor-x** [comment]
https://github.com/seamapi/fake-seam-connect/pull/38#issuecomment-1652732954

**Comment by razor-x** [comment]
The docker pr is what made is larger. Ah, this is because we added a new entrypoint.

**Pull request merged**
